spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: root
  flyway:
    baseline-on-migrate: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.yandex.ru
    username: 
    password:
    port: 465
    protocol: smtps
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

page-size: 12
mail:
  debug: true
address: http://localhost:8080/users/activate/

upload-path: C:\\projects\\e-shop\\img